// 由 `cargo run --bin export_types` 產生 —— 不要手改，改了下次重產就沒了。
// 對應的 Rust 定義在 backend/src/{models,handlers,services,utils}/。

// This file has been generated by Specta. Do not edit this file manually.
export type AddTagRequest = {
	tag_name: string,
	color: string | null,
};

/**  AI 標籤搜尋結果 */
export type AiTagSearchResult = {
	path: string,
	name: string,
	tag: string,
	confidence: number | null,
};

export type AudioMetadata = {
	title: string | null,
	artist: string | null,
	album: string | null,
	duration_seconds: number | null,
};

export type AuditLog = {
	id: number,
	user_id: number,
	action: string,
	target: string,
	details: string | null,
	ip_address: string | null,
	created_at: string,
};

export type BatchOperationRequest = {
	paths: string[],
	destination: string | null,
};

/**  一致性檢查結果 */
export type ConsistencyCheckResult = {
	total_db_entries: number,
	removed_orphans: number,
	message: string,
};

/**  容器配置 */
export type ContainerConfig = {
	hostname: string | null,
	env: string[],
	cmd: string[],
	working_dir: string | null,
};

/**  容器詳細資訊 */
export type ContainerDetails = {
	id: string,
	name: string,
	image: string,
	state: ContainerState,
	config: ContainerConfig,
	network_settings: NetworkSettings,
	mounts: MountPoint[],
};

/**  容器狀態 */
export type ContainerState = {
	status: string,
	running: boolean,
	paused: boolean,
	restarting: boolean,
	started_at: string | null,
	finished_at: string | null,
	exit_code: number | null,
};

/**  容器統計資訊 */
export type ContainerStats = {
	cpu_percent: number | null,
	memory_usage: number,
	memory_limit: number,
	memory_percent: number | null,
	network_rx: number,
	network_tx: number,
	block_read: number,
	block_write: number,
};

/**  容器摘要資訊（用於列表顯示） */
export type ContainerSummary = {
	id: string,
	names: string[],
	image: string,
	image_id: string,
	state: string,
	status: string,
	created: number,
	ports: PortMapping[],
};

export type CreateFolderRequest = {
	/**
	 *  父目錄路徑，例如 "Documents"。空字串表示根目錄
	 *  Parent directory path, e.g. "Documents". Empty string means root.
	 */
	path: string,
	/**
	 *  新資料夾名稱，例如 "New Folder"
	 *  New folder name, e.g. "New Folder"
	 */
	folder_name: string,
};

export type CreateShareLinkRequest = {
	file_path: string,
	password: string | null,
	expires_in_seconds: number | null,
};

export type CreateUploadLinkRequest = {
	target_path: string,
	password: string | null,
	expires_in_seconds: number | null,
	max_files: number | null,
	max_file_size: number | null,
};

export type DiskInfo = {
	name: string,
	mount_point: string,
	total_space: number,
	available_space: number,
	disk_type: string,
};

export type EmptyResponse = Record<string, never>;

/**
 *  我的最愛檔案資訊（包含 starred_at 時間戳）
 *  Favorite file info with starred_at timestamp
 */
export type FavoriteFileInfo = {
	name: string,
	path: string,
	is_dir: boolean,
	size: number,
	modified: string,
	mime_type: string | null,
	starred_at: string,
};

export type FileInfo = {
	name: string,
	path: string,
	is_dir: boolean,
	size: number,
	modified: string,
	mime_type: string | null,
	metadata: FileMetadata | null,
	tags: Tag[],
	is_starred: boolean,
};

export type FileMetadata = ({ Image: ImageMetadata }) & { Audio?: never; Video?: never } | ({ Audio: AudioMetadata }) & { Image?: never; Video?: never } | ({ Video: VideoMetadata }) & { Audio?: never; Image?: never } | "None";

export type FileVersion = {
	version_id: string,
	timestamp: number,
	size: number,
};

export type GpuInfo = {
	name: string,
	memory_total: number,
	memory_used: number,
	memory_free: number,
	utilization: number | null,
	temperature: number,
};

/**  HLS 狀態響應 */
export type HlsStatusResponse = {
	status: string,
	qualities: string[],
	master_playlist: string | null,
	job_id: string | null,
};

export type ImageMetadata = {
	width: number | null,
	height: number | null,
	camera_model: string | null,
	date_time: string | null,
};

/**  鏡像摘要資訊 */
export type ImageSummary = {
	id: string,
	repo_tags: string[],
	repo_digests: string[],
	created: number,
	size: number,
	virtual_size: number | null,
};

export type InitUploadRequest = {
	file_path: string,
	file_name: string,
	total_size: number,
};

export type InitUploadResponse = {
	upload_id: string,
	/**  已上傳的位元組數（若為 resume 則回傳目前已上傳大小） */
	uploaded_size: number | null,
	/**  status: "created" | "resuming" */
	status: string | null,
};

export type Job = {
	id: string,
	job_type: string,
	status: string,
	progress: number,
	created_at: string,
	updated_at: string,
	error: string | null,
};

export type JobStatus = "pending" | "processing" | "completed" | "failed";

export type JobUpdate = {
	job_id: string,
	status: JobStatus,
	progress: number,
	error: string | null,
};

/**  Docker 日誌條目 */
export type LogEntry = {
	stream: string,
	message: string,
};

export type LoginRequest = {
	username: string,
	password: string,
};

/**  第一階段登入回應：要嘛直接登入完成（無 2FA），要嘛需要 2FA code */
export type LoginResponse = 
/**  一般使用者（沒啟用 2FA）— cookie 已發，前端正常導向 */
EmptyResponse | 
/**  需要 2FA 驗證 */
{ requires_2fa: boolean; 
/**  短效 token（5 分鐘），下一步 verify code 時帶回 */
temp_token: string };

/**  掛載點資訊 */
export type MountPoint = {
	mount_type: string,
	source: string | null,
	destination: string,
	mode: string | null,
	rw: boolean,
};

/**  網絡資訊 */
export type NetworkInfo = {
	ip_address: string | null,
	gateway: string | null,
	mac_address: string | null,
};

/**  網絡設置 */
export type NetworkSettings = {
	ip_address: string | null,
	gateway: string | null,
	networks: { [key in string]: NetworkInfo },
};

/**  網絡摘要資訊 */
export type NetworkSummary = {
	id: string,
	name: string,
	driver: string,
	scope: string,
	internal: boolean,
	attachable: boolean,
	ingress: boolean,
	ipam_driver: string | null,
	containers: number,
};

/**  端口映射資訊 */
export type PortMapping = {
	private_port: number,
	public_port: number | null,
	port_type: string,
};

export type ProcessInfo = {
	pid: number,
	name: string,
	cpu_usage: number | null,
	memory_bytes: number,
	memory_percent: number | null,
};

/**  拉取鏡像請求 */
export type PullImageRequest = {
	image: string,
	tag?: string,
};

export type RegisterRequest = {
	username: string,
	password: string,
	/**
	 *  邀請碼（必填，用於限制註冊）
	 *  Invite code (required to restrict registration)
	 */
	invite_code: string | null,
};

/**  重新掃描結果 */
export type RescanResult = {
	success: boolean,
	message: string,
};

export type SearchResult = {
	path: string,
	name: string,
	score: number | null,
};

/**  分享連結元數據響應 */
export type ShareInfoResponse = {
	id: string,
	file_name: string,
	file_size: number,
	mime_type: string | null,
	is_directory: boolean,
	is_password_protected: boolean,
	expires_at: string | null,
	created_at: string,
};

export type ShareLinkResponse = {
	id: string,
	url: string,
	expires_at: string | null,
};

/**  停止/重啟容器的請求體 */
export type StopContainerRequest = {
	/**  超時秒數（預設 10 秒） */
	timeout: number | null,
};

export type SystemStatus = {
	cpu_usage: number | null,
	cpu_temp: number | null,
	total_memory: number,
	used_memory: number,
	total_swap: number,
	used_swap: number,
	disks: DiskInfo[],
	gpu: GpuInfo | null,
	top_processes: ProcessInfo[],
	ups: UpsInfo | null,
};

export type Tag = {
	name: string,
	color: string | null,
};

export type TaggedFile = {
	path: string,
	name: string,
	is_dir: boolean,
	size: number,
	modified: string,
};

export type TimelineGroup = {
	date: string,
	files: FileInfo[],
};

export type TwoFactorDisableRequest = {
	password: string,
	/**  6 位 code 或 backup code */
	code: string,
};

/**  2FA 第二階段登入請求 */
export type TwoFactorLoginRequest = {
	temp_token: string,
	/**  6 位 TOTP code 或 backup code（後者帶 dash，例如 ABCDE-F2345） */
	code: string,
};

/**  啟用 2FA 第一步回應：把 secret + otpauth URI 給前端，前端畫 QR */
export type TwoFactorSetupResponse = {
	secret: string,
	otpauth_uri: string,
};

/**  2FA 狀態查詢回應 */
export type TwoFactorStatusResponse = {
	enabled: boolean,
	/**  還剩多少 backup codes */
	backup_codes_remaining: number,
};

export type TwoFactorVerifySetupRequest = {
	/**  用 Authenticator app 掃完後輸入的第一個 6 位 code */
	code: string,
};

/**  啟用 2FA 完成後的回應：8 組 backup codes（一次性顯示，user 必須記下來） */
export type TwoFactorVerifySetupResponse = {
	backup_codes: string[],
};

export type UploadLinkInfoResponse = {
	id: string,
	target_folder: string,
	is_password_protected: boolean,
	expires_at: string | null,
	max_files: number | null,
	max_file_size: number | null,
	uploaded_count: number,
	created_at: string,
};

export type UploadLinkResponse = {
	id: string,
	url: string,
	expires_at: string | null,
};

export type UploadSession = {
	id: string,
	user_id: number,
	file_path: string,
	file_name: string,
	total_size: number,
	uploaded_size: number,
	created_at: string,
	updated_at: string,
};

export type UpsInfo = {
	/**  NUT ups.status，例如 "OL"（吃市電）/ "OB"（吃電池）/ "OL CHRG" */
	status: string,
	/**  是否正常吃市電（OL 且非 OB） */
	online: boolean,
	/**  電池電量 % */
	battery_charge: number | null,
	/**  剩餘可用秒數 */
	battery_runtime: number | null,
	/**  UPS 負載 % */
	ups_load: number | null,
	/**  輸入（市電）電壓 */
	input_voltage: number | null,
	/**  輸出電壓 */
	output_voltage: number | null,
	/**  機型 */
	model: string | null,
	/**  這份資料的時間戳（host 端寫入時間） */
	updated_at: string | null,
};

export type User = {
	id: number,
	username: string,
	created_at: string,
	/**  0 = 未啟用，1 = 已啟用 */
	totp_enabled: number,
};

export type UserTag = {
	name: string,
	color: string | null,
	count: number,
};

export type VideoMetadata = {
	width: number | null,
	height: number | null,
	duration_seconds: number | null,
};

/**
 *  WebSocket 客戶端發送的訊息類型
 * 
 *  `rename_all = "snake_case"`：與 JSON 面上其餘部分（欄位名、`JobStatus`）一致。
 */
export type WsClientMessage = 
/**  訂閱 Docker 容器統計 */
{ type: "subscribe_docker_stats"; payload: {
	container_id: string,
} } | 
/**  取消訂閱 Docker 容器統計 */
{ type: "unsubscribe_docker_stats"; payload: {
	container_id: string,
} } | 
/**  Ping (保持連線) */
{ type: "ping" };

/**
 *  WebSocket 伺服器發送的訊息類型。
 * 
 *  ⚠️ **這是伺服器送出的唯一信封** —— 每一則訊息都必須是本 enum 的某個 variant。
 *  先前 `JobUpdate` 是直接把裸物件序列化丟上同一條 socket（沒有 `type` 欄位），
 *  於是前端的 `switch (msg.type)` 拿到 `undefined`，背景工作的進度與完成通知
 *  從來沒有送達過。要加新的推播就在這裡加 variant，不要另闢管道。
 */
export type WsServerMessage = 
/**  背景工作進度更新（來源是 `utils::queue` 的 broadcast） */
{ type: "job_update"; payload: JobUpdate } | 
/**  Docker 容器統計數據 */
{ type: "docker_stats"; payload: {
	container_id: string,
	cpu_percent: number | null,
	memory_usage: number,
	memory_limit: number,
	memory_percent: number | null,
	network_rx: number,
	network_tx: number,
	block_read: number,
	block_write: number,
	timestamp: number,
} } | 
/**  Docker 統計錯誤 */
{ type: "docker_stats_error"; payload: {
	container_id: string,
	error: string,
} } | 
/**  Pong 回應 */
{ type: "pong" } | 
/**  錯誤訊息 */
{ type: "error"; payload: {
	message: string,
} };
